---
- name: Configure SSH
  hosts: pc
  vars:
    user: guangzong

  tasks:
    - name: add user to sudoer
      become: true
      lineinfile:
        path: /etc/sudoers
        regexp: "^# %wheel ALL=(ALL) ALL NOPASSWD: ALL"
        line: "%wheel ALL=(ALL) ALL NOPASSWD: ALL"
        validate: "visudo -cf %s"
    # remove sudo password for wheel user

    - name: Disable password login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?PasswordAuthentication"
        line: "PasswordAuthentication no"
      become: true

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted
      become: true

    - name: Install fish shell
      package:
        name: fish
        state: present
      become: true
