---
- name: Configure after install
  hosts: pc
  vars:
    kerserver: hkps://keys.openpgp.org
    my_key: 20AE4BA8FF696FB5E21AE9D0636538D58AF1006D
    user: guangzong
  tasks:
    - name: get gpg public key from key server
      command: gpg --keyserver {{ kerserver }} --recv-keys {{ my_key }}
      become: false
    - name: locale
      lineinfile:
        path: /etc/locale.gen
        line: en_US.UTF-8 UTF-8
        state: present
      become: true
    - name: Change root shell to fish
      user:
        name: root
        shell: /usr/bin/fish
      become: true

    - name: Change user shell to fish
      user:
        name: "{{ user }}"
        shell: /usr/bin/fish
      become: true
    - name: locale-gen
      command: locale-gen
      become: true
    - name: install software
      become: true
      pacman:
        name: "{{ item }}"
        state: present
      with_items:
        - alacritty
        - nvidia
        - yadm
    - name: disable sleep (this is require when using nvidia driver) sleep will cause problem.
      command: |
       systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target
      become: true
    
    - name: install nix and configure it
      pacman:
        name: nix
        state: present
      become: true
    - name: enable nix-daemon.service
      systemd:
        name: nix-daemon
        enabled: yes
        state: started
      become: true

    - name: add user to nix-users group
      user:
        name: "{{ user }}"
        groups: nix-users
        append: yes
      become: true
    - name: nix channel
      command: nix-channel --add https://nixos.org/channels/nixos-23.11 nixpkgs
      become: false
    - name: nix channel update
      command: nix-channel --update
      become: false 



