---
- name: restore archlinux configs
  hosts: control
  become: false
  vars:
    backup_file: "/tmp/config-backup.tar.gz"
    remote_backup_file: "local/server-backup/arch-config-backup.tar.gz"

  tasks:
    - name: download configs from minio
      command:
        cmd: "mcli cp {{ remote_backup_file }} {{ backup_file }}"
    - name: extract configs
      command:
        cmd: "tar -xzvf {{ backup_file }} -C ~/"

    - name: Remove temporary archive file
      file:
        path: "{{ backup_file }}"
        state: absent
