---
# brefore using this script, should check each block. Most operation are not recoverable and not idempotent.
- name: Install arclinux 2
  hosts: pc
  become: true

  vars:
    timezone: "America/New_York"
    password: "password"
    new_user_name: "guangzong"
    disk: "/dev/nvme1n1" # this should be check before using this script.

  tasks:
    - name: Update archlinux-keyring
      command: pacman -Sy archlinux-keyring --noconfirm

    - name: Install base packages
      command: pacstrap /mnt base base-devel linux linux-firmware dhcpcd docker docker-compose openssh grub

    - name: Generate fstab (check manually, this may not work - i don't know why. manually execute the command)
      command: genfstab -U /mnt >> /mnt/etc/fstab
