---
# Brefore using this script, you should check each block carefully. Most operation are not recoverable and not idempotent.
- name: Install arclinux
  hosts: pc
  become: true

  vars:
    timezone: "America/New_York"
    password: "password"
    new_user_name: "guangzong"
    disk: "/dev/sda" # this should be check before using this script.

  tasks:
    - name: Enable NTP (Network Time Protocol)
      command: timedatectl set-ntp true

    - name: Set Timezone
      command: timedatectl set-timezone {{ timezone }}

    - name: Create partition table
      parted:
        device: "{{ disk }}"
        label: gpt

    - name: Create 1GB FAT32 partition
      parted:
        device: "{{ disk }}"
        number: 1
        part_end: 1GB
        flags: [boot, esp]
        state: present
        label: gpt
      become: true
      become_user: root

    - name: Format first partition as FAT32
      command: "mkfs.fat -F32 {{ disk }}p1"
      become: true
      become_user: root

    - name: Create second partition
      parted:
        device: "{{ disk }}"
        number: 2
        part_start: 1GB
        state: present
        label: gpt
      become: true
      become_user: root

    - name: Format second partition as ext4
      command: "mkfs.ext4 {{ disk }}p2"
      become: true
      become_user: root

    - name: Mount second partition to /mnt
      mount:
        src: "{{ disk }}p2"
        path: /mnt
        fstype: ext4
        state: mounted
      become: true
      become_user: root

    - name: Create /mnt/boot/EFI directory
      file:
        path: /mnt/boot/EFI
        state: directory
        mode: "0755"
      become: true
      become_user: root

    - name: Mount first partition to /mnt/boot/EFI
      mount:
        src: "{{ disk }}p1"
        path: /mnt/boot/EFI
        fstype: vfat
        state: mounted
