---
- name: Configure SSH
  hosts: managed
  vars:
    my_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAB...your_public_key_here...8H1w=="
    user: zong

  tasks:
    - name: Disable password login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
      become: true

    - name: Update authorized keys
      authorized_key:
        user: "{{ user }}"
        state: present
        key: "{{ my_key }}"
      become: true

    - name: Add users to allow users
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?AllowUsers'
        line: 'AllowUsers {{ user }} gitea'
      become: true

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted
      become: true

    - name: Install fish shell
      package:
        name: fish
        state: present
      become: true

    - name: Change root shell to fish
      user:
        name: root
        shell: /usr/bin/fish
      become: true

    - name: Change user shell to fish
      user:
        name: "{{ user }}"
        shell: /usr/bin/fish
      become: true
