---
- name: Bakcup nginx
  hosts: managed
  vars:
    backup_directory: "backups"

  tasks:
    - name : Get current date
      set_fact:
        current_date: "{{ ansible_date_time.date }}"
    - name: backup configurations
      become: true
      copy:
        src: "{{ item }}"
        dest: "/tmp/{{ backup_directory }}/{{current_date}}/"
        remote_src: yes
      with_items:
        - /etc/nginx
    - name: package nginx to one tar file
      command:
        cmd: "tar -czvf nginx.tar.gz nginx"
        chdir: "/tmp/{{ backup_directory }}/{{current_date}}"
    - name: upload nginx file to R2
      command:
        cmd: "mcli cp nginx.tar.gz r2/backup/nginx.tar.gz"
        chdir: "/tmp/{{ backup_directory }}/{{current_date}}"
    - name: remove tmp files
      become: true
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/{{ backup_directory }}/{{current_date}}/nginx.tar.gz
        - /tmp/{{ backup_directory }}/{{current_date}}/nginx

    - name: backup letsencrypt
      become: true
      copy:
        src: "{{ item }}"
        dest: "/tmp/{{ backup_directory }}/{{current_date}}/"
        remote_src: yes
      with_items:
        - /etc/letsencrypt
    - name: package letsencrypt to one tar file
      become: true
      command:
        cmd: "tar --mode=644 -czvf letsencrypt.tar.gz letsencrypt"
        chdir: "/tmp/{{ backup_directory }}/{{current_date}}"

    - name: upload letsencrypt file to R2
      command:
        cmd: "mcli cp letsencrypt.tar.gz r2/backup/letsencrypt.tar.gz"
        chdir: "/tmp/{{ backup_directory }}/{{current_date}}"

    - name: remove tmp files
      become: true
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/{{ backup_directory }}/{{current_date}}/letsencrypt.tar.gz
        - /tmp/{{ backup_directory }}/{{current_date}}/letsencrypt
