---
- name : Backup gitea
  hosts: managed
  become: true
  vars:
    backup_directory: "backups"
    database_name: "gitea"

  tasks:
    - name: Get current date
      set_fact:
        current_date: "{{ ansible_date_time.date }}"

    - name: Backup gitea
      file:
        path: "/tmp/{{ backup_directory }}/{{current_date}}"
        state: directory
        owner: gitea
        group: gitea
      become: true

    - name: Dump gitea data
      become: true
      become_user: gitea
      command:
        cmd: "gitea dump -c /etc/gitea/app.ini -f gitea.zip"
        chdir: "/tmp/{{ backup_directory }}/{{current_date}}"

    - name: Backup gitea file
      synchronize:
        src: /tmp/{{ backup_directory }}/{{current_date}}/gitea.zip
        dest: /tmp/{{ backup_directory }}/{{current_date}}/gitea.zip
        owner: gitea
        group: gitea
        mode: '0644'

    - name: Delete gitea file
      file:
        path: /tmp/{{ backup_directory }}/{{current_date}}/gitea.zip
        state: absent

    - name: Backup config files
      fetch:
        src: "{{ item }}"
        dest: "/tmp/{{ backup_directory }}/{{current_date}}/"
      with_items:
        - /etc/gitea/app.ini
        - /usr/lib/systemd/system/gitea.service
        - /etc/systemd/system/multi-user.target.wants/gitea.service
        # - /tmp/{{ backup_directory }}/{{current_date}}/gitea.zip

        # - /etc/nginx/conf.d/gitea.conf
        # delegate_to: localhost
