---
- name : Backup gitea
  hosts: managed
  vars:
    backup_directory: "backups"
    database_name: "gitea"

  tasks:
    - name: Get current date
      set_fact:
        current_date: "{{ ansible_date_time.date }}"

    - name: Backup gitea
      file:
        path: "/tmp/{{ backup_directory }}/{{current_date}}"
        state: directory
        mode: '0777'
      become: true

    - name: Dump gitea data
      become: true
      become_user: gitea
      command:
        cmd: "gitea dump -c /etc/gitea/app.ini -f gitea.zip"
        chdir: "/tmp/{{ backup_directory }}/{{current_date}}"

    - name: Backup config files
      become: true
      become_user: gitea
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/tmp/{{ backup_directory }}/{{current_date}}/"
        remote_src: yes
      with_items:
        - /etc/gitea/app.ini
        - /usr/lib/systemd/system/gitea.service

    - name: package to one tar file
      become: true
      become_user: gitea
      command:
        cmd: "tar --mode=644 -cvf gitea.tar gitea.zip app.ini gitea.service"
        chdir: "/tmp/{{ backup_directory }}/{{current_date}}"

    - name: Upload gitea file to R2
      command:
        cmd: "mcli cp gitea.tar r2/backup/gitea.tar"
        chdir: "/tmp/{{ backup_directory }}/{{current_date}}"

    - name: Delete gitea files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/{{ backup_directory }}/{{current_date}}/gitea.zip
        - /tmp/{{ backup_directory }}/{{current_date}}/app.ini
        - /tmp/{{ backup_directory }}/{{current_date}}/gitea.service
        - /tmp/{{ backup_directory }}/{{current_date}}/gitea.tar.gz
