# this file is used to backup docker container config files and data
#
---
- name: Backup docker files
  hosts: managed
  become: true
  vars:
    backup_directory: "backups"

  tasks:
    - name: Get current date
      set_fact:
        current_date: "{{ ansible_date_time.date }}"
    - name: Create backup working directory
      become: true
      file:
        path: "/tmp/{{ backup_directory }}/{{current_date}}"
        state: directory
        mode: 0777
    - name: Copy docker data
      become: false
      copy:
        src: "{{ item }}"
        dest: "/tmp/{{ backup_directory }}/{{current_date}}/"
        remote_src: yes
      with_items:
        - /home/zong/cloudreve
        - /usr/lib/systemd/system/cloudreve.service
        - /home/zong/ghost
        - /home/zong/jellyfin
        - /home/zong/raddar
        - /home/zong/blogB
        - /home/zong/homer
        - /home/zong/memos
        - /home/zong/portainer
        - /home/zong/photoprism
    - name: package to one tar file
      command:
        cmd: "tar --mode=644 -czvf docker.tar.gz cloudreve ghost jellyfin raddar blogB homer memos portainer photoprism"
        chdir: "/tmp/{{ backup_directory }}/{{current_date}}"
    - name: Upload backup file (docker.tar.gz) to R2
      command:
        cmd: "mcli cp docker.tar.gz r2/backup/docker.tar.gz"
        chdir: "/tmp/{{ backup_directory }}/{{current_date}}"
