# This is an ansible playbook to update the system
---
- name: Update all hosts
  hosts: server, pc
  become: true

  tasks:
    - name: Full system upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true
