---
- name: Configure yarn and go development environment 
  hosts: managed
  become: true

  tasks:
    - name: Install yarn
      pacman:
        name: "{{ item }}"
        state: present
      loop:
        - yarn
        - go
        - tea
      