# This is an ansible playbook to update the system
---
- name: Update all hosts
  hosts: server
  become: true

  tasks:
    - name: disconnect nordvpn 
      become: false
      command: nordvpn disconnect
      
    - name: Remove specific sports if they exist
      become: true
      ansible.builtin.command:
        cmd: "ip rule del sport {{ item.port }} table main priority {{ item.priority }}"
      loop:
        - { port: 22, priority: 100 }
        - { port: 80, priority: 101 }
        - { port: 443, priority: 102 }
        - { port: 2002, priority: 103 }
      ignore_errors: yes
      failed_when: false