---
- name: Backup ssh configs/minio client config
  hosts: control
  become: false
  vars:
    backup_file: "/tmp/config-backup.tar.gz"
    remote_backup_file: "local/server-backup/arch-config-backup.tar.gz"

  tasks:
    - name: Package configs
      command:
        cmd: |
          tar -czvf  {{ backup_file }}
          -C ~/
          .ssh
          .mcli
          .gitconfig
          .ideavimrc
          .config/conky


    - name: Upload backup file to minio
      command:
        cmd: "mcli cp {{ backup_file }} {{ remote_backup_file }}"

    - name: Remove temporary archive file
      file:
        path: "{{ backup_file }}"
        state: absent
