---
- name: Backup nginx and let's encrypt
  hosts: managed
  become: true
  vars:
    remote_backup_file: "local/server-backup/nginx-backup.tar.gz"

  tasks:
    - name: Package nginx and let's encrypt files into one tar archive
      become: true
      command:
        cmd: "tar -czvf /tmp/nginx.tar.gz /etc/nginx /etc/letsencrypt"

    - name: Upload nginx file to minio
      command:
        cmd: "mcli cp /tmp/nginx.tar.gz {{ remote_backup_file }}"

    - name: Remove temporary archive file
      file:
        path: /tmp/nginx.tar.gz
        state: absent
