- name: Backup vaultwarden
  hosts: managed
  become: true

  vars:
    bak_dir: "/tmp/vaultwarden"
    remote_backup_file: "local/server-backup/vaultwarden.tar.gz"

  tasks:
    - name: Create backup working directory
      file:
        path: "{{ bak_dir }}"
        state: directory

    - name: Package vaultwarden data and config files
      command:
        cmd: "tar -czvf vaultwarden.tar.gz /var/lib/vaultwarden /etc/vaultwarden.env"
        chdir: "{{ bak_dir }}"

    - name: Upload backup file to minio
      become: true
      command:
        cmd: "mcli cp vaultwarden.tar.gz {{ remote_backup_file }}"
        chdir: "{{ bak_dir }}"

    - name: Remove backup file
      file:
        path: "{{ bak_dir }}/vaultwarden.tar.gz"
        state: absent
