# this file is used to backup docker container config files and data
#
---
- name: Backup docker files
  hosts: managed
  become: true
  vars:
    bak_dir: "/tmp/docker"

  tasks:
    - name: Create backup working directory
      become: true
      file:
        path: "{{ bak_dir }}"
        state: directory
        mode: 0777
    - name: package to one tar file
      become: true
      command:
        cmd: "tar -czvf docker.tar.gz
              /home/zong/cloudreve
              /usr/lib/systemd/system/cloudreve.service
              /home/zong/ghost
              /home/zong/jellyfin
              /home/zong/raddar
              /home/zong/blogB
              /home/zong/homer
              /home/zong/memos
              /home/zong/portainer"
              # /home/zong/photoprism"
        chdir: "{{ bak_dir }}"
          # - name: Upload backup file (docker.tar.gz) to R2
          #   command:
          #     cmd: "mcli cp docker.tar.gz r2/backup/docker.tar.gz"
          #     chdir: "/tmp/{{ bak_dir }}/{{current_date}}"
    - name: upload to R2
      become: false
      command:
        cmd: "mcli cp {{ bak_dir }}/docker.tar.gz r2/backup/docker.tar.gz"
