---
- name: Backup drone and upload to R2
  hosts: managed
  vars:
    backup_file: "/tmp/drone.tar.gz"
    remote_bakup_file: "local/server-backup/drone.tar.gz"

  tasks:

    - name: Package drone files into one tar file
      become: true
      command:
        cmd: |
          tar -czvf {{ backup_file }}
          -C /
          var/lib/drone
          etc/systemd/system/drone-runner-docker.service.d
          etc/systemd/system/drone-runner-exec.service.d
          etc/systemd/system/drone.service.d

    - name: Upload drone backup file to minio
      become: true
      command: "mcli cp {{ backup_file }} {{ remote_bakup_file }}"
