---
- name: Configure SSH
  hosts: localhost

  tasks:
    - name: Full system upgrade
      become: true
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: install software
      become: true
      pacman:
        name: "{{ item }}"
        state: present
      with_items:
        - fdupes # duplicate file finder
        - kicad
        - kicad-library
        - kicad-library-3d
        - os-prober

        - wireguard-tools
        - openresolv # dependency of wg-quick

        - speedtest-cli # speedtest
        - xterm
        - git # git
        - nvidia # nvidia driver
        - gnome-shell # desktop environment
        - gdm # display manager
        - chromium # browser
        - ibus-rime # input method
        - gnome-terminal # terminal
        - telegram-desktop # telegram
        - pycharm-community-edition # pycharm
        - python-pytorch-opt-cuda
        - archlinux-wallpaper
        - gnome-tweaks
        - gnome-control-center
        - gnome-keyring
        - wqy-microhei # chinese support
        - ansible
        - doublecmd-qt5
        - less
        - fuse2
        - gnome-shell-extension-appindicator
        - gnome-shell-extensions
        - conky
        - gnome-system-monitor
        - papirus-icon-theme
        - gnome-shell-extension-dash-to-panel
        - pacutils
        - bc # bc is an arbitrary precision numeric processing language.
        - fzf # for vim and command line finder
        - xclip # for vim copy
        - cmake # cpp build system
        - nodejs # for neovim with copilot plugin
        - ttf-jetbrains-mono-nerd # nerd font
        - clang
        - pyright
        - ripgrep
        - ninja
        - noto-fonts-emoji
        - curl
        - texlab
        - lua-language-server
        - texlive
        - zathura
        - zathura-pdf-mupdf
        - arm-none-eabi-gcc
        - arm-none-eabi-gdb
        - arm-none-eabi-newlib
        - arm-none-eabi-binutils
        - rustup
        - bluez
        - rubber # for latex
        - eog # image viewer
        - npm
        - meld
        - neovide
        - rsync
        - vlc
        - usbutils
        - rhythmbox
        - arc-gtk-theme
        - htop
        - minio-client
        - mlocate
        - nautilus
        - go
    - name: remove package
      become: true
      pacman:
        name: "{{ item }}"
        state: absent
      with_items:
        - xterm # xterm when gnome-terminal not working
        - dconf-editor
        - python-torchvision-cuda
        - pavucontrol
        - gnome-console
        - alacritty
        - gnome-music
        - neovim-qt
        - lollypop # music player

    # - name: gdm set to x11
    #   become: true
    #   lineinfile:
    #     path: /etc/gdm/custom.conf
    #     regexp: "^#?WaylandEnable"
    #     line: "WaylandEnable=false"
    - name: try to update locale
      become: true
      locale_gen:
        name: en_US.UTF-8
        state: present

    # - name: enable gdm
    #   become: true
    #   service:
    #     name: gdm
    #     state: started
    #     enabled: true
