---
- name: jabref install and update
  hosts: localhost
  vars:
    version: 5.12-1
    package_name: jabref-bin

  tasks:
    - name: if /tmp/{{ package_name }} exists, remove it
      become: false
      file:
        path: /tmp/{{ package_name }}
        state: absent

    - name: make aur package `{{ package_name }}`
      become: false
      shell: |
        cd /tmp
        git clone https://aur.archlinux.org/{{ package_name }}.git
        cd {{ package_name }}
        makepkg

    - name: install {{ package_name }}
      become: true
      pacman:
        name: /tmp/{{ package_name }}/{{ package_name }}-{{ version }}-x86_64.pkg.tar.zst
        state: present
