---
- name: sioyek install and update
  hosts: pc
  vars:
    version: 2.0.0-5
    package_name: sioyek

  tasks:
    - name: install dependencies
      become: true
      pacman:
        name: qt5-3d
        state: present
    - name: if /tmp/{{ package_name }} exists, remove it
      become: false
      file:
        path: /tmp/{{ package_name }}
        state: absent

    - name: make aur package `{{ package_name }}`
      become: false
      shell: |
        cd /tmp
        git clone https://aur.archlinux.org/{{ package_name }}.git
        cd {{ package_name }}
        makepkg --skipchecksums

    - name: install {{ package_name }}
      become: true
      pacman:
        name: /tmp/{{ package_name }}/{{ package_name }}-{{ version }}-x86_64.pkg.tar.zst
        state: present
