---
- name: sublime install and update
  hosts: pc
  vars:
    version: 2091-2
    package_name: sublime-merge
    gpg_key: 1EDDE2CDFC025D17F6DA9EC0ADAE6AD28A8F901A
    key_server: hkps://keyserver.ubuntu.com # hkps://keys.openpgp.org
    
  tasks:
    - name: get gpg key
      become: false
      shell: |
        gpg --keyserver {{ key_server }} --recv-keys {{ gpg_key }}
    - name: if /tmp/{{ package_name }} exists, remove it
      become: false
      file:
        path: /tmp/{{ package_name }}
        state: absent

    - name: make aur package `{{ package_name }}`
      become: false
      shell: |
        cd /tmp
        git clone https://aur.archlinux.org/{{ package_name }}.git
        cd {{ package_name }}
        makepkg --skipchecksums

    - name: install {{ package_name }}
      become: true
      pacman:
        name: /tmp/{{ package_name }}/{{ package_name }}-{{ version }}-x86_64.pkg.tar.zst
        state: present
