---
- name: Con
  hosts: pc
  vars:
    user: zong # change this to your user name
    newpassword: "password" # change this to your new password
    newrootpassword: "password" # change this to your new password

  tasks:
    - name: update root password
      become: true
      command:
        cmd: "echo 'root:{{ newrootpassword }}' | chpasswd"

    - name: update user password
      become: true
      command:
        cmd: "echo '{{ user }}:{{ newpassword }}' | chpasswd"
