---
- name: Configure Gitea
  hosts: managed
  become: true
  vars:
    tmp_file : "/tmp/gitea.tar.gz"

  tasks:
    - name: Update pacman package cache
      pacman:
        update_cache: yes

    - name: Install Gitea
      pacman:
        name: gitea
        state: present

    - name: Fetch data from R2
      command:
        cmd: "mcli cp r2/backup/gitea.tar.gz {{ tmp_file }}"

    - name: Extract data from bakcup
      command:
        cmd: "tar -xzvf {{ tmp_file }} -C /"

    - name: Start gitea Service
      service:
        name: gitea
        state: started

    - name: delete tmp file
      file:
        path: "{{ tmp_file }}"
        state: absent
