---
- name: Configure nginx
  hosts: managed
  become: true
  vars:
    bak_file: "/tmp/nginx.tar.gz"
  tasks:
    - name: Install Nginx
      pacman:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - nginx
        - certbot-nginx

    - name: Fetch data from R2
      command:
        cmd: "mcli cp r2/backup/nginx.tar.gz {{ bak_file }}"

    - name: Extract data from bakcup
      command:
        cmd: "tar -xzvf {{ bak_file }} -C /"

    - name: Start Nginx Service
      service:
        name: nginx
        state: started

    - name: delete temporary backup file
      file:
        path: "{{ bak_file }}"
        state: absent
