---
- name: Configure vaultwarden
  hosts: managed
  become: true
  vars:
    tmp_file : "/tmp/vaultwarden.tar.gz"

  tasks:
    - name: Update pacman package cache
      pacman:
        update_cache: yes

    - name: Install vaultwarden
      pacman:
        name: "{{ item }}"
        state: present
      with_items:
        - vaultwarden
        - vaultwarden-web

    - name: Fetch data from R2
      command:
        cmd: "mcli cp r2/backup/vaultwarden.tar.gz {{ tmp_file }}"

    - name: Extract data from bakcup
      command:
        cmd: "tar -xzvf {{ tmp_file }} -C /"

    - name: Start vaultwarden Service
      service:
        name: vaultwarden
        state: started

    - name: delete tmp file
      file:
        path: "{{ tmp_file }}"
        state: absent
